// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJNyZwDFSfDqD_Yx2ZGLhnfFnvDN8DbU',
    appId: '1:572761103431:web:3c61f698c907013ed8e562',
    messagingSenderId: '572761103431',
    projectId: 'flutter-listoftodo-firebase',
    authDomain: 'flutter-listoftodo-firebase.firebaseapp.com',
    storageBucket: 'flutter-listoftodo-firebase.appspot.com',
    measurementId: 'G-1LQKJHS3DR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfnjGUlNxm5wlBDV3d6KsLX6yC8oJbtv8',
    appId: '1:572761103431:ios:f72b696c58afe6f9d8e562',
    messagingSenderId: '572761103431',
    projectId: 'flutter-listoftodo-firebase',
    storageBucket: 'flutter-listoftodo-firebase.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfnjGUlNxm5wlBDV3d6KsLX6yC8oJbtv8',
    appId: '1:572761103431:ios:f72b696c58afe6f9d8e562',
    messagingSenderId: '572761103431',
    projectId: 'flutter-listoftodo-firebase',
    storageBucket: 'flutter-listoftodo-firebase.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOGsnFJOwHsGQsfhMLkDU6HllBahPNtg8',
    appId: '1:572761103431:android:b8fcfb9a59a1cbf8d8e562',
    messagingSenderId: '572761103431',
    projectId: 'flutter-listoftodo-firebase',
    storageBucket: 'flutter-listoftodo-firebase.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEJNyZwDFSfDqD_Yx2ZGLhnfFnvDN8DbU',
    appId: '1:572761103431:web:8a4b5f6b0fe09a86d8e562',
    messagingSenderId: '572761103431',
    projectId: 'flutter-listoftodo-firebase',
    authDomain: 'flutter-listoftodo-firebase.firebaseapp.com',
    storageBucket: 'flutter-listoftodo-firebase.appspot.com',
    measurementId: 'G-Y1VFEYR0KR',
  );
}
